In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("Social_network_Ads.csv")

In [4]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
from sklearn import preprocessing

In [7]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [8]:
label_encoder=preprocessing .LabelEncoder()

In [18]:
x=df.iloc[:,[2,3]].values
y=df.iloc[:,4].values

In [19]:
print(x[:3,:])
print('-'*15)
print(y[:3])

[[   19 19000]
 [   35 20000]
 [   26 43000]]
---------------
[0 0 0]


In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [24]:
print(x_train[:3])
print('_'*15)
print(y_train[:3])
print('_'*15)
print(x_test[:3])
print('_'*15)
print(y_test[:3])





[[    44  39000]
 [    32 120000]
 [    38  50000]]
_______________
[0 1 0]
_______________
[[   30 87000]
 [   38 50000]
 [   35 75000]]
_______________
[0 0 0]


In [26]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
x_train=sc_X.fit_transform(x_train)
x_test=sc_X.transform(x_test)

In [30]:
print(x_train[:3])
print('_'*15)
print(x_test[:3])

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]]
_______________
[[-0.80480212  0.50496393]
 [-0.01254409 -0.5677824 ]
 [-0.30964085  0.1570462 ]]


In [34]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0,solver='lbfgs')
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

In [35]:
print(x_test[:10])
print('_'*15)
print(y_pred[:3])


[[-0.80480212  0.50496393]
 [-0.01254409 -0.5677824 ]
 [-0.30964085  0.1570462 ]
 [-0.80480212  0.27301877]
 [-0.30964085 -0.5677824 ]
 [-1.10189888 -1.43757673]
 [-0.70576986 -1.58254245]
 [-0.21060859  2.15757314]
 [-1.99318916 -0.04590581]
 [ 0.8787462  -0.77073441]]
_______________
[0 0 0]


In [36]:
print(y_pred[:20])
print(y_test[:20])

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]


In [39]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)
print(cm)

[[65  3]
 [ 8 24]]


In [52]:
from matplotlib.colors import ListedColormap
x_set, y_set ,y_train, y_train
x1, x2= np.meshgrid(np.arange(start=x_set[:,0] .min()-1, stop= x_set[:,0].max()+ 1, ste 
                         np.arange(start=x_set[:,1].min -1,stop=x_set[:,1].max()+ 1,ste
plt.contourf(x1,x2,classifier.predict(np.array[x1.ravel(),x2.ravel()]).T).reshape(x1.shape)
                                         alpha=0.6, cmap ListedColormap('red', 'green')))
plt.xlin(x1.min(), xi.max())
plt.ylin(x2.ain(), xz.max())
for i, j enumerate(np.unique(y_set)):
                    plt.scatter(x_set[y_set==j,0],x_set[y_set==j,1],
                               c=ListedColormap(('red','green'))(i),label=j)
plt.title('Logistic Regression ('Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

SyntaxError: positional argument follows keyword argument (2265754006.py, line 4)

In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


In [54]:
data = pd.read_csv('Social_Network_Ads.csv')


In [55]:
data = pd.get_dummies(data, columns=['Gender'], drop_first=True)

# Separate the features (X) and the target variable (y)
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
# Create a logistic regression classifier
classifier = LogisticRegression()

# Fit the model on the training data
classifier.fit(X_train, y_train)

LogisticRegression()

In [57]:
y_pred = classifier.predict(X_test)


In [58]:
# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)
TN = cm[0, 0]
FP = cm[0, 1]
FN = cm[1, 0]
TP = cm[1, 1]

print("TN : ",TN)
print("FP : ",FP)
print("FN : ",FN)
print("TP : ",TP)

TN :  20
FP :  24
FN :  16
TP :  20


In [59]:
# Compute accuracy
accuracy = accuracy_score(y_test, y_pred)

# Compute error rate
error_rate = 1 - accuracy

# Compute precision
precision = precision_score(y_test, y_pred)

# Compute recall
recall = recall_score(y_test, y_pred)

In [60]:
print("Accuracy : ", accuracy)
print("Error rate : ", error_rate)
print("Precision : ", precision)
print("Recall : ", recall)

Accuracy :  0.5
Error rate :  0.5
Precision :  0.45454545454545453
Recall :  0.5555555555555556


In [62]:
IRIS.head()

NameError: name 'IRIS' is not defined